spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:mem:test
    username: root
    password: 1234
#    initialization-mode: ALWAYS
#    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: H2
    show-sql: true
    generate-ddl: false
spring.cache.cache-names: getTime,currentTimeMillis
spring.cache.caffeine.spec: maximumSize=100,expireAfterWrite=5s